### ISSUE TITLE
Auto add non found record to entity

### ISSUE THREAD

**Issue by jandelange** [AuraQ/AutoCompleteForMendix#12]
First, I like this widget very much. 

When a record not is found, the "no results found text" will appear. We are looking for a function where not a text is shown, but a small button with the possibility to start a Microflow. With that MF you can add functionality yourself like:
- Automatic add the string to the linked entity
- Add the value to another field'

Jan de Lange ( jan@jadela.nl )

**Comment by lindski** [comment]
Thanks :)

I took a quick look and select2 allows you to return html when no results are found so this should be possible. Will need to investigate a bit more though... not sure when I'll be able to do this as I'm a bit busy at the moment but hopefully can find some time in the next few weeks

Cheers

**Comment by jandelange** [comment]
Thx for your Quick response. Should be great.

Op 26 sep. 2016 10:08 schreef "Iain Lindsay" <notifications@github.com>:

**Comment by lindski** [comment]
Have added support for this in commit a84d83c

There is a new tab 'No Results' that allows you to render the 'No results' text as a button. You can also select a microflow to execute when the button is clicked. Looks like it is only possible to pass objects into microflows called from custom widgets so you also need to select an attribute in the data context that will be populated with the current search term when the no results microflow is executed.

Test project contains an example of this and an updated widget is available in the dist folder

Let me know if this covers your requirement

**Comment by jandelange** [comment]
I have tested the new feature and it works great. This opens a lot of nice possibilities

**Comment by lindski** [comment]
Excellent

This will also be available from the app store in version 2.1.0 of the widget
