### ISSUE TITLE
On change of association in background doesn't trigger refresh for widget

### ISSUE THREAD

**Issue by dkho87** [AuraQ/AutoCompleteForMendix#13]
First off, thanks for this great widget!

It seems that if I have an association which is empty (say: PurchaseOrder_Country), whenever an On change microflow is triggered from another random field, which populates the PurchaseOrder_Country association (change object, refresh = yes), this change is not reflected in the widget. I have double checked this with the default reference selector and see that this one is properly updated, whereas the contents of the widget remains empty.

**Comment by lindski** [comment]
Thanks!

There was a slight issue in the code that detects changes in the context object so while it was updating the page correctly if the association was cleared, it wasn't doing anything if the association was set.

I've just fixed this in c51aaa8

An updated widget is available in the dist folder. Let me know if this solves it for you

**Comment by lindski** [comment]
sorry, dist folder is only on my local machine! You'll need to take the widget from the widgets folder in the test project

**Comment by dkho87** [comment]
Hi Iain, thanks for the swift action! Just tried the MPK from your fix, and this seems to work correctly!
