### ISSUE TITLE
Validation error not passed to tabcontainer badge

### ISSUE THREAD

**Issue by dkho87** [AuraQ/AutoCompleteForMendix#16]
I've noticed that if you have the widget in a tabcontainer (or multiple instances), and a Show validation message is triggered, these validation errors are not added to the tabcontainer level which displays the number of validation errors in a badge.

So instead of showing a badge with the number 3, right now the value 1 is displayed if I have three fields, of which 2 are the AutoComplete widget.

Any chance you could have a look at this?
Thanks in advance!

**Comment by lindski** [comment]
Apologies for the delay in picking this up.

Will need to investigate this and see if I can find an example of this in one of Mendix's own widgets

**Comment by dkho87** [comment]
Hi Iain, no worries! Am already happy that you're helping me out.
Have a look at https://github.com/mendix/SearchInput I recently requested the same fix over there as well. 👍

**Comment by lindski** [comment]
Ah perfect, that saved me a job, have just copied it from that widget!

Fix has been uploaded in commit ed75a72. Widget can be grabbed from test project

Let me know if this sorts it for you

**Comment by dkho87** [comment]
Wow that was fast! I just tested it and everything seems to work nicely. Thanks a bunch!
