### ISSUE TITLE
Deprecated JS functions

### ISSUE THREAD

**Issue by thendricks86** [AuraQ/AutoCompleteForMendix#19]
This widget uses a range of JS functions that will be discontinued in Mendix 7 which is due to release shortly. To support Mendix 7 and later, some JS will need to be changed:

mxui.js?636162850359943084:5 Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.f.getText @ mxui.js?636162850359943084:5
mxui.js?636162850359943084:48 DEPRECATED: mxui.dom.{tagName} will be removed in version 7.0. Use mxui.dom.create API for creating elements.d @ mxui.js?636162850359943084:48
mxui.js?636162850359943084:48 DEPRECATED: mxui.dom.builder.create will be removed in version 7.0. Use mxui.dom.create instead.d @ mxui.js?636162850359943084:48
mxui.js?636162850359943084:48 DEPRECATED: mxui.dom.{tagName} will be removed in version 7.0. Use mxui.dom.create API for creating elements.d @ mxui.js?636162850359943084:48
mxui.js?636162850359943084:48 DEPRECATED: mxui.dom.builder.create will be removed in version 7.0. Use mxui.dom.create instead.

**Comment by lindski** [comment]
Thanks for the heads up on this... will look to replace these in v3 which I'm hoping to finish off over Christmas

**Comment by lindski** [comment]
The warning about use of Synchronous XMLHttpRequest doesn't appear to be linked to the widget.

I have updated the use of mxui/dom to remove calls to the deprecated functions in commit e5d65cb.

I'm not ready to do a release of v3 yet but there is a copy in the test project (in the v3 branch) if you wanted to take a look.

**Comment by lindski** [comment]
V3 now available from the appstore

[https://appstore.home.mendix.com/link/app/2695/AuraQ-Limited/AutoComplete-widget](https://appstore.home.mendix.com/link/app/2695/AuraQ-Limited/AutoComplete-widget)
