### ISSUE TITLE
Evil code! deleting define.amd will kill many other libs!!!

### ISSUE THREAD

**Issue by Andries-Smit** [AuraQ/AutoCompleteForMendix#21]
Are you kidding me?

This line of code did kill the startup of an app in latest build of PhoneGap.
https://github.com/AuraQ/AutoCompleteForMendix/blob/master/src/AutoCompleteForMendix/lib/jqwrapper.js#L2

The async behaviour is not guaranteed to back in time and set it again, causing lots of errors and wasting much my time.

Sorry to so blunt, hope you fix it.

Cheers, Andries

**Comment by lindski** [comment]
Sorry this caused you problems

This approach was copied from a Mendix widget in an attempt to work around loading conflicts between multiple jQuery libraries.

Will revert back to the default approach for loading jQuery.

**Comment by Andries-Smit** [comment]
The trouble is that Query does not play well with others. Would discourage to use it in any widget. 
Is this pull request the solution https://github.com/AuraQ/AutoCompleteForMendix/pull/7/files ?

**Comment by JelteMX** [comment]
It's bad I never spotted it in the review of the widget, before submiting it to the AppStore. I might even unpublish old versions if this breaking a lot of libs. The pull request should fix this, please do so a.s.a.p.

**Comment by lindski** [comment]
Will do it now

Can't avoid having jQuery in there as the underlying library I use relies on it

**Comment by lindski** [comment]
Release 2.1.1 created and submitted to appstore for approval

**Comment by Andries-Smit** [comment]
Thanks a lot!
