### ISSUE TITLE
Request: Add Search delay

### ISSUE THREAD

**Issue by lenn123** [AuraQ/AutoCompleteForMendix#22]
The widget is highly appreciated!

It would be great if a search delay (in milliseconds) can be added before the search is executed.

**Comment by lindski** [comment]
Thanks!

Before processing the results, the widget checks to ensure that the search term hasn't changed. If it has changed then it doesn't process the results (it expects a new result set matching the new term). 

Are you seeing results appear that do not match the search term?

**Comment by lenn123** [comment]
No, we are using a microflow to fill in our search results which is calling a webservice. In order to prevent the webservice call in it self it would be nice to limit this based on a preset delay. This delay is basically a timeout that calls the _findMatches functions, kind of like in the Onchangeinputbox https://github.com/mendix/OnchangeInputbox. Reasons to limit the webservice calls are cost effeciency (each call costs money) but also resource effeciency as webservice calls are relativly costly server operations.

**Comment by lindski** [comment]
Ok, I understand the problem. Will have a look and see what we can do.

iain

**Comment by lindski** [comment]
Hi,

I've added a new parameter in commit 1edd02b called 'Search Delay' (under the 'Search' tab) that allows you to define a delay in milliseconds. The widget now waits for the user to stop typing for this configured time period before the search is executed. 

An updated widget is available in the test project... can you check to see if this meets your expectations and then I will create a release and get it published to the appstore.

Cheers

iain

**Comment by lenn123** [comment]
Hi,

I just tested the new version of the widget. This is exactly as I would expect it to work! Thank you very much for the quick change. It is highly appreciated!

**Comment by lindski** [comment]
Great, have created a 3.1.1 release... will close this issue when its available on the app store

**Comment by lindski** [comment]
Version 3.1.1 now available on the app store

**Comment by lenn123** [comment]
Thanks again!!
