### ISSUE TITLE
Search Xpath constrained by (context) does not work

### ISSUE THREAD

**Issue by tswart** [AuraQ/AutoCompleteForMendix#23]
Search Xpath constrained by (context) does not work.
The Xpath constrained by (context) does not constraint the number of objects.
The context object is not yet committed. 
Notice: When using a normal reference selector the constrained by (1 path) work fine.

**Comment by lindski** [comment]
Hello

The 'constrained by' parameters are used to execute an XPath query against the database that navigates over the context object so it does require the context object to be committed. It is not possible to exactly match the out of the box 'constrained by' functionality.

Thanks

Iain

**Comment by tswart** [comment]
Thanks Lain.
