### ISSUE TITLE
Tabbing from an autocomplete widget while in search mode results in loss of focus

### ISSUE THREAD

**Issue by Narev** [AuraQ/AutoCompleteForMendix#28]
When you are in search mode and you press tab you completely loose focus. I tracked down the issue to a known issue of [select2 4384](https://github.com/select2/select2/issues/4384).  The best result i got so far is that when pressing tab the focus will shift to the select span and from there you are able to continue the normal tab route, but this would still require users to press tab twice in order to jump to the following Mendix widget. Did you have a go at this and if not could you look into this.

**Comment by hganzeboom** [comment]
It would be great if this issue could be fixed.

**Comment by lindski** [comment]
Sorry, project demands have taken up all my time recently.

Will try and look into this by the end of the week

**Comment by hganzeboom** [comment]
Hi Lindski, Thank you for your quick reply :-)

**Comment by lindski** [comment]
Took a look at this over lunch... I've applied the workaround in the linked issue and it now seems to be working.

I have also added an extra property to the Control Display tab called 'Select On Close' which will select the highlighted item when the control closes (e.g. when tabbing out)... the default is set to false so it doesn't impact any existing use of the widget

The latest widget is available in the test project... I'll also create a release for this for the app store (version 3.2.0)

**Comment by hganzeboom** [comment]
Great!! Thank you very much Lindsay! We will test the solution right away!

**Comment by lindski** [comment]
Added in 3.2.0
