### ISSUE TITLE
GetGuid error

### ISSUE THREAD

**Issue by MarcoKeijsersAdoptiq** [AuraQ/AutoCompleteForMendix#29]
I have implemented this widget in my project with a relation and xpath search. The users that is logged in can only select the source record when it is linked to him (constraint on database level > xpath constraint). When the record can not be retrieved an error popsup in the widget. The errors occurs from line 424 till 427. See
            if(referencedObjectGuid !== null && referencedObjectGuid !== "") {                        
                mx.data.get({
                    guid: referencedObjectGuid,
                    callback: dojoLang.hitch(this, function(obj){                             
                        this._processResults([obj],this._formatCurrentValue, null);

**Comment by JamesRamm** [comment]
Same problem.
It seems that from time to time `mx.data.get` returns `null` with no error message.
I dont know if this is a general problem or related to this widget in specific

**Comment by lindski** [comment]
I have applied a fix for this in v5 of the widget... now, if an attempt is made to retrieve the referenced object and it comes back as null, I am displaying an empty dropdown.
