### ISSUE TITLE
On Change Event triggers multiple times

### ISSUE THREAD

**Issue by aareich** [AuraQ/AutoCompleteForMendix#34]
When nested within a list view, the on change event is triggered anywhere from 3-16 times on a single change. 

Mendix version 7.8

**Comment by erqvu** [comment]
Have the same issue, has forced me to stop using the widgets and go back to dropdown widget. Big shame as this widget is a lot better

**Comment by tieniber** [comment]
Issue was due to the widget calling initialiseControl() multiple times when its update() function was called
