### ISSUE TITLE
Request: Microflow options for On Change events

### ISSUE THREAD

**Issue by PineappleTorte** [AuraQ/AutoCompleteForMendix#35]
I have an on-change microflow that can take some time to execute - I'm looking for the microflow options menu available on native mendix functionality where you can control blocking progress spinners and loading messages. Any chance this is in the works?

**Comment by lindski** [comment]
This will be added in the next release. The widget in the test project includes the extra properties to support this if you want to take a look however the final build of version 4 will be a bit different as I'm aiming to add some more fixes over the next couple of weeks.

**Comment by lindski** [comment]
This has now been added to v4 of the widget, available in the app store
