### ISSUE TITLE
 TypeError: $.throttle is not a function

### ISSUE THREAD

**Issue by gajduk-mansystems** [AuraQ/AutoCompleteForMendix#36]
I am using the latest Auto Complete widget in our project (v 3.2.0).

I have configured an on change microflow. Everything seems to work correctly, but everytime before the on change mciroflow is called I can see an error in the browser console:

`Uncaught TypeError: $.throttle is not a function`

I looked up the javascript line that caused the error from the debugger:

` $.throttle( 50,self._execMf(self._contextObj.getGuid(), self.onChangeMicroflow));`

If I set a breakpoint I can indeed see that throttle is undefined. Still the microflow is called and everything runs fine, except that the browser console shows an error.

Am I missing some configuration/dependencies?

**Comment by lindski** [comment]
Hi, this line does not exist in the autocomplete widget code... are you sure it is not being thrown by another widget in your project?

**Comment by gajduk-mansystems** [comment]
I can confirm this is coming from the auto complete widget. I have the following line in widgets.js

        ` $.throttle( 50, this._execMf(self._contextObj.getGuid(), self.cacheSearchMicroflow, function(objs){`

However I can see that this line does not occur in the github repo. It is likely that someone customized this widget in my project without logging that change. 
Sorry for wasting your time.
