### ISSUE TITLE
Sort of Result doesn't work on 7.11

### ISSUE THREAD

**Issue by erqvu** [AuraQ/AutoCompleteForMendix#37]
I use the autocomplete widget a lot and the optionslist is not sorting anymore. 
I'm running 7.11 
For now I have started using MF and sort the list, when it's urgent. But would prefer that the option wroks again.

**Comment by lindski** [comment]
Hi, I am using a sort order and it is working correctly for me. I am using 7.13.1

Could you give me some more details on your issue so I can investigate further?

**Comment by lindski** [comment]
Unable to reproduce. Feel free to reopen the issue if you still believe it to be a problem
