### ISSUE TITLE
Non Editable state is not supported

### ISSUE THREAD

**Issue by erqvu** [AuraQ/AutoCompleteForMendix#38]
We widgets does not have a non editabale state. I often open a screen and give the user the choice to edit. So I open readonly. I try to use one page for both read and edit mode. Saves maintenacce and development time

**Comment by lindski** [comment]
There are two properties, 'Disabled' and 'Disabled via attribute' that allow you to control whether the dropdown is disabled or not. Do either of these fit your requirement?

**Comment by lindski** [comment]
The widget now shows as disabled when placed in a read only data view. This fix is included in v4 of the widget, available in the app store
