### ISSUE TITLE
Auto open

### ISSUE THREAD

**Issue by jandelange** [AuraQ/AutoCompleteForMendix#47]
An option which opens the dropdown list directly, so the user can start typing without any mouse click.
I have a situation where speed is important The customer has to do four things:
- create record ( i did that with an hotkey )
- the page opens and get focus on the autocompleteformendix witget
- the customer should check the record ( sometimes a date should be modified )
- Save and Print ( is also one hotkey )
So everything is done with the keyboard except opening of the autocompleteformendix witget

**Comment by lindski** [comment]
I have added a new option 'Open on focus' (Control Display tab) that allows you to configure whether the dropdown should auto open or not. 

This is available in v6.0.0 in the app store

**Comment by jandelange** [comment]
Great Lian,

thx i will implement this asap to my customer, he will be happy

Jan
________________________________
Van: Iain Lindsay <notifications@github.com>
Verzonden: vrijdag 15 mei 2020 09:39
Aan: AuraQ/AutoCompleteForMendix <AutoCompleteForMendix@noreply.github.com>
CC: Jan de Lange <jan@jadela.nl>; Author <author@noreply.github.com>
Onderwerp: Re: [AuraQ/AutoCompleteForMendix] Auto open (#47)


Closed #47<https://github.com/AuraQ/AutoCompleteForMendix/issues/47>.

**Comment by jandelange** [comment]
and it works.......
________________________________
Van: Iain Lindsay <notifications@github.com>
Verzonden: vrijdag 15 mei 2020 09:39
Aan: AuraQ/AutoCompleteForMendix <AutoCompleteForMendix@noreply.github.com>
CC: Jan de Lange <jan@jadela.nl>; Author <author@noreply.github.com>
Onderwerp: Re: [AuraQ/AutoCompleteForMendix] Auto open (#47)


Closed #47<https://github.com/AuraQ/AutoCompleteForMendix/issues/47>.
