### ISSUE TITLE
Mx 8.3 - Client Warning, mx.ui.action depreceated, use mx.data.action instead

### ISSUE THREAD

**Issue by L-Shel** [AuraQ/AutoCompleteForMendix#53]
Hi there

When using V5.0 of this widget, in Mendix 8.3, it logs a client level warning every time a search runs

"DEPRECATED: mx.ui.action. Use mx.data.action directly instead. -- will be removed in version: 10.0"

Doesn't look like it's causing any issues, but less warning in the log is always nice if it's an easy fix

Cheers

**Comment by nickhoogenboom** [comment]
Having the same issue in Mendix 8.8.

Is this something that will be solved in the near future?

**Comment by lindski** [comment]
This deprecated method has been replaced in v6.0.0, now available in the app store

**Comment by hello-mendix-world** [comment]
@lindski works like a charm, warning is not visible anymore. Many thanks!

**Comment by Muhammadwajih** [comment]
Dear @hello-mendix-world  Did you find a suitable solution for this "DEPRECATED: logger, use mx.logger instead -- will be removed in version: 11.0" I recently Upgrade my application from Mendix 8.18 to Mendix 9.6.11
