### ISSUE TITLE
No results displayed by default

### ISSUE THREAD

**Issue by Liamhanninen** [AuraQ/AutoCompleteForMendix#74]
Apologies if this turns out to be expected behavior. I've set one up where search = Xpath. The search function works as expected. But before I even search I would expect to see a list of options when I first click the drop-down. See screenshot - I have not typed anything yet but I don't see any options. If this is expected - is there any setting for me to provide a microflow to grab an inital list of objects to display when user opens the dropdown? I am using Mendix Studio Pro 9.6.0.
![image](https://user-images.githubusercontent.com/15257781/139564180-65b28141-57a7-4745-a1fb-579abb057f75.png)

**Comment by lindski** [comment]
Hi Liam

If you set the Minimum Input Length to 0 (Search tab), the widget will execute the search immediately.

Cheers

Iain

**Comment by Liamhanninen** [comment]
Thanks so much. This is a pretty cool feature maybe you could put a note underneath saying just that: "Note: If you set the Minimum Input Length to 0 (Search tab), the widget will execute the search immediately.". This behavior makes it feel more like a normal drop-down with the added search benefit. But maybe that's obvious to other users. Just an idea. Thanks again!

**Comment by Liamhanninen** [comment]
I had one other question. I realized the Mendix forum was a better place for it. If you have time, at your convenience please check it out: https://forum.mendix.com/link/questions/110825

**Comment by pratleymatthew** [comment]
This issue has been fixed in v6.1.0, now available in the app store. I've had a quick look at your forum question. 

Unfortunately, with regards to your forum post, there's currently no way to use this widget for entity attributes.
