### ISSUE TITLE
Exception thrown first time execution

### ISSUE THREAD

**Issue by markvwd** [AuraQ/AutoCompleteForMendix#9]
the first time the _loadCurrentValue is executed, it seems that the _contextObj is still null. From what i can see, the _contextObj is only given a value when the update function is called.

Because this value is null, an exception is thrown (and swallowed by the mendix code) on this line:

`var referencedObjectGuid = this._contextObj.get(this._reference)`

**Comment by lindski** [comment]
_loadCurrentValue is only being called at the bottom of the update method, if obj (which gets assigned to _contextObj) is not null.

Are you using the latest version of the widget? What version of Mendix are you running?

Do you have an example project that demonstrates this issue?

**Comment by markvwd** [comment]
I think i see the problem, in the postCreate function there is a call to _updateRendering 
(in the version I just downloaded from the appstore it is not commented out, as i can see in the version on github)

Correct me if I'm wrong, but i seem to recall the _updateRendering also called the _loadCurrentValue function. (after updating from the appstore I overwrite the version that gave me an error)

(after doing an update from the appstore the problem with this exception does not exist anymore)

**Comment by lindski** [comment]
ok great, will close this off
